const fs=require('fs');
let txt = fs.readFileSync('src/components/InteractiveGlobeMap/Globe.tsx','utf8');
txt=txt.replace(/drilledContinent/g, 'dCR');
txt=txt.replace(/dCR:/g,'drilledContinent:');
txt=txt.replace(/dCR,/g,'drilledContinent,');
txt=txt.replace(/\[dCR\]/g,'[drilledContinent]');
txt=txt.replace(/dCR/g,'drilledContinentRef.current');
const inj="const drilledContinentRef = useRef(drilledContinent);\n  useEffect(() => { drilledContinentRef.current = drilledContinent; }, [drilledContinent]);\n  const selectedRef = useRef(selectedCity);";
txt=txt.replace("const selectedRef = useRef(selectedCity);", inj);
fs.writeFileSync('src/components/InteractiveGlobeMap/Globe.tsx',txt,'utf8');
