export type Artwork = {
  id: string;
  firestoreId?: string;
  source?: string;
  name: string;
  artist: string;
  year: number;
  image: string;
  fallbackImages?: string[];
  thumb?: string;
  lq?: string;
  variants?: {
    webp?: Record<string, string>;
    avif?: Record<string, string>;
    jpg?: Record<string, string>;
  };
  imageLocal?: string;
  roomId: string;
  exhibitionName: string;
  exhibitionTitle: string;
  date?: string;
  dimension?: string;
  sourceUrl?: string;
  createdAt?: unknown;
  type?: '2D' | '3D' | 'video' | 'unknown';
  isArchival?: boolean;
  onView?: boolean;
  duration?: string;
  medium?: string;
  technique?: string;
  materials?: string;
  category?: string;
  artworkType?: string;
  description?: string;
  categories?: string[];
  isHighlight?: boolean;
  metadata?: Record<string, string>;
  location?: string;
  youtubeId?: string;
  mediaType?: 'image' | 'video';
  publicDomain?: boolean;
  rights?: string;
};
