const fs = require('fs');
let d = fs.readFileSync('src/data/exhibitions.js', 'utf8');

const map = {
  'rodin-collection': 'rodin-collection.json',
  'rodin-sculptures': 'rodin-sculptures.json',
  'rodin-gravures': 'rodin-gravures.json',
  'rodin-peintures': 'rodin-peintures.json',
  'pompidou-drawing-collection': 'pompidou-drawing-collection.json',
  'pompidou-newmedia-collection': 'pompidou-newmedia-collection.json',
  'pompidou-design-collection': 'pompidou-design-collection.json',
  'pompidou-cinema-collection': 'pompidou-cinema-collection.json',
  'pompidou-painting-collection': 'pompidou-unmapped-paintings.json',
  'bordeaux-collection': 'bordeaux-collection.json',
  'musee-conde-collection': 'musee-conde-collection.json',
  'picasso-paris-collection': 'picasso-paris-collection.json',
  'carnavalet-the-collection': 'carnavalet-the-collection.json',
  'hamburger-kunsthalle-drawings': 'hamburger-kunsthalle-drawings.json',
  'hamburger-kunsthalle-video': 'hamburger-kunsthalle-video.json',
  'mamcs-strasbourg-collection': 'mamcs-strasbourg-collection.json',
  'mamcs-paintings': 'mamcs-strasbourg-paintings-collection.json',
  'mamcs-drawings': 'mamcs-strasbourg-drawings-collection.json',
  'mamcs-photography': 'mamcs-strasbourg-photography-collection.json',
  'mamcs-graphic': 'mamcs-strasbourg-graphicdesign-collection.json',
  'mad-paris-collection': 'mad-paris-collection.json',
  'musee-toulouse-lautrec-collection': 'toulouse-lautrec-collection.json',
  'mba-lyon-collection': 'mba-lyon-collection.json',
  'rouen-mba-collection': 'rouen-mba-collection.json',
  'flv-collection': 'flv-collection.json',
  'kroller-muller-photography': 'kroller-muller-photography.json',
  'kroller-muller-film-video': 'kroller-muller-film-video.json',
  'belvedere-malerei': 'belvedere-malerei-collection.json',
  'lacma-japanese-prints': 'lacma-list-japanese-prints.json',
  'lacma-drawings-51': 'lacma-list-drawings-51.json',
  'met-ny-on-view-paintings-enriched': 'met-ny-on-view-paintings-enriched.json',
  'met-ny-on-view-paintings': 'met-ny-on-view-paintings.json',
  'musee-armee-collection': 'musee-armee-collection.json',
  'musee-armee-dessin': 'musee-armee-dessin.json',
  'musee-armee-photographie': 'musee-armee-photographie.json',
  'musee-armee-peinture': 'musee-armee-peinture.json',
  'musba-bordeaux-drawings': 'musba-bordeaux-drawings-collection.json',
  'musba-bordeaux-paintings': 'musba-bordeaux-paintings-collection.json',
  'musee-grenoble-paintings': 'musee-grenoble-paintings-collection.json',
  'musee-grenoble-drawings': 'musee-grenoble-drawings-collection.json',
  'national-museum-korea-missing': 'national-museum-korea-missing.json',
  'vam-paintings': 'vam-paintings.json',
  'vam-portraits': 'vam-portraits.json',
  'vam-photographs': 'vam-photographs.json',
  'vam-posters': 'vam-posters.json',
  'mplus-collection-highlights': 'mplus-collection-highlights.json',
  'lacma-list': 'lacma-list.json',
  'tate-artworks': 'tate-artworks.json',
  'fine-arts-be-complete': 'fine-arts-be-complete.json',
  'wawel-collection': 'wawel-collection.json',
  'reina-sofia-on-display': 'reina-sofia-on-display.json',
  'mamcs-strasbourg': 'mamcs-strasbourg.json',
  'toulouse-lautrec-collection': 'toulouse-lautrec-collection.json',
  'tate-st-ives-artworks': 'tate-st-ives-artworks.json',
  'egyptian-museum-cairo-collection': 'egyptian-museum-cairo-collection.json',
  'lille-pba-collection': 'lille-pba-collection.json',
  'kim-tschang-yeul-collection': 'kim-tschang-yeul-collection.json',
  'musee-granet-collection': 'musee-granet-collection.json',
  'palais-beaux-arts-lille-collection': 'palais-beaux-arts-lille-collection.json',
  'tate-modern': 'tate-modern.json',
  'banrep-collection': 'banrep-collection.json',
  'tate-britain': 'tate-britain.json',
  'nmec-collection': 'nmec-collection.json',
  'vam': 'vam.json',
  'tate-st-ives': 'tate-st-ives.json',
  'ngv-trove-collection-fixed': 'ngv-trove-collection-fixed.json',
  'tate-liverpool': 'tate-liverpool.json',
  'zeitz-mocaa-collection': 'zeitz-mocaa-collection.json'
};

for (const [id, file] of Object.entries(map)) {
  const rx = new RegExp('(\\{[^}]*id:\\s*\"' + id + '\"[^}]*endDate:\\s*\"Permanent\")\\s*\\}', 'g');
  d = d.replace(rx, '$1, collectionFile: \"' + file + '\" }');
}

fs.writeFileSync('src/data/exhibitions.js', d);
console.log('Fixed missing collectionFiles!');