#!/usr/bin/env python3
"""
Jina-CLIP-v2 missing-permanent embedder
=======================================
Parallel pipeline to `run_siglip_missing_permanent.py`, swapping the
encoder for **jina-clip-v2** (1024-dim, multilingual, Matryoshka).

It reads the SAME queue — `permanent_missing_pending.jsonl`
(`{"id": ..., "e": exhibition_id, "i": image_url}`, generated by
`scripts/build_permanent_missing.py`) — and embeds every artwork whose id
is not already in `jina_processed_ids.txt`.

Why a separate file set (not `siglip_processed_ids.txt`)?
  Jina vectors are 1024-dim and live in a SEPARATE Vectorize index, so the
  two encoders track their own progress independently. Re-running either is
  a no-op for items it has already embedded.

Save guarantees (identical to the SigLIP script — nothing gets lost):
  1. Every embedding is written to disk
     (`embedding_results/jina_clip_missing_permanent_embeddings.jsonl`)
     BEFORE its id is added to `jina_processed_ids.txt`.
  2. Cloudflare upload is a separate phase; a disk write counts as success
     even if the upload fails. Failed uploads → `jina_upload_retry_missing.jsonl`
     (replay later with the same /upsert endpoint — no GPU re-run needed).
  3. All file writes are guarded by a threading.Lock.

What the operator (you) provides:
  - A GPU (Colab/Modal/local CUDA or Apple MPS).
  - `pip install -U "transformers>=4.44" timm einops pillow requests torch`
  - A Cloudflare Vectorize index of dimension 1024 + cosine, and a Worker
    `/upsert` route that writes to it. Point JINA_UPSERT_URL at that route.
    (The SigLIP index is 768-dim — do NOT reuse it.)

Run:
  JINA_UPSERT_URL="https://<your-worker>/upsert" \
    python3 scripts/run_jina_clip_missing_permanent.py
  # add  --no-upload  to embed-to-disk only (upload later), or
  #      --limit N    to process only the first N pending items (smoke test)
"""
import argparse
import datetime
import json
import os
import threading
import warnings
from concurrent.futures import ThreadPoolExecutor
from io import BytesIO
from pathlib import Path

import requests
import urllib3
from PIL import Image
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

warnings.filterwarnings("ignore")
urllib3.disable_warnings()

# ── Paths ───────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
PENDING_FILE   = ROOT / os.environ.get('JINA_PENDING', 'jina_missing_pending.jsonl')
PROCESSED_FILE = ROOT / 'jina_processed_ids.txt'
OUTPUT_DIR     = ROOT / 'embedding_results'
OUTPUT_FILE    = OUTPUT_DIR / 'jina_clip_missing_permanent_embeddings.jsonl'
RETRY_FILE     = ROOT / 'jina_upload_retry_missing.jsonl'
STATE_FILE     = ROOT / 'jina_state_missing_permanent.json'
OUTPUT_DIR.mkdir(exist_ok=True)

# ── Model & runtime config ──────────────────────────────────────────────
WORKER_UPSERT_URL = os.environ.get("JINA_UPSERT_URL", "").strip()
MODEL_ID          = os.environ.get("JINA_MODEL_ID", "jinaai/jina-clip-v2")
EMBED_DIM         = int(os.environ.get("JINA_DIM", "1024"))   # Matryoshka: 64..1024
GPU_BATCH         = int(os.environ.get("JINA_GPU_BATCH", "8"))
UPLOAD_BATCH      = int(os.environ.get("JINA_UPLOAD_BATCH", "50"))
PREFETCH_WORKERS  = int(os.environ.get("JINA_PREFETCH", "6"))
DOWNLOAD_TIMEOUT  = 12
UPLOAD_TIMEOUT    = 30
DOWNLOAD_HEADERS  = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/122.0.0.0 Safari/537.36",
    "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
}

session = requests.Session()
_retries = Retry(total=2, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504])
session.mount('http://',  HTTPAdapter(max_retries=_retries, pool_connections=20, pool_maxsize=20))
session.mount('https://', HTTPAdapter(max_retries=_retries, pool_connections=20, pool_maxsize=20))

file_lock = threading.Lock()


# ── State / queue helpers (mirror the SigLIP script) ───────────────────
def load_state():
    state = {"total_success": 0, "total_failed": 0, "total_upserted": 0,
             "total_upload_retry": 0,
             "started_at": datetime.datetime.now().isoformat()}
    if STATE_FILE.exists():
        try:
            state.update(json.loads(STATE_FILE.read_text()))
        except Exception:
            pass
    return state


def save_state(state):
    with file_lock:
        STATE_FILE.write_text(json.dumps(state, ensure_ascii=False, indent=2))


def load_processed():
    processed = set()
    if PROCESSED_FILE.exists():
        with open(PROCESSED_FILE, encoding='utf-8') as f:
            for line in f:
                s = line.strip()
                if s:
                    processed.add(s)
    return processed


def load_pending(processed):
    if not PENDING_FILE.exists():
        raise SystemExit(f"[fatal] {PENDING_FILE} missing — run "
                         "scripts/build_permanent_missing.py first")
    out, skipped = [], 0
    with open(PENDING_FILE) as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            try:
                rec = json.loads(s)
            except Exception:
                continue
            if not rec.get('id') or not rec.get('i'):
                continue
            if rec['id'] in processed:
                skipped += 1
                continue
            out.append(rec)
    return out, skipped


def download_image(item):
    art_id, img_url, e_id = item['id'], item['i'], item.get('e', '')
    try:
        resp = session.get(img_url, timeout=DOWNLOAD_TIMEOUT, verify=False,
                           headers=DOWNLOAD_HEADERS)
        if resp.status_code == 200:
            return art_id, e_id, img_url, Image.open(BytesIO(resp.content)).convert("RGB"), None
        return art_id, e_id, img_url, None, f"HTTP {resp.status_code}"
    except Exception as ex:
        return art_id, e_id, img_url, None, str(ex)[:120]


def upload_batch(batch):
    if not batch:
        return True, None
    if not WORKER_UPSERT_URL:
        return False, "JINA_UPSERT_URL not set"
    try:
        resp = session.post(WORKER_UPSERT_URL, json={"vectors": batch}, timeout=UPLOAD_TIMEOUT)
        if resp.status_code == 200:
            return True, None
        return False, f"HTTP {resp.status_code}: {resp.text[:120]}"
    except Exception as ex:
        return False, str(ex)[:120]


def append_jsonl(path, rec):
    with file_lock:
        with open(path, 'a', encoding='utf-8') as f:
            f.write(json.dumps(rec, ensure_ascii=False) + '\n')


def append_processed(art_id):
    with file_lock:
        with open(PROCESSED_FILE, 'a', encoding='utf-8') as f:
            f.write(art_id + '\n')


# ── Main ────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-upload', action='store_true', help="embed to disk only")
    ap.add_argument('--limit', type=int, default=0, help="process only first N pending")
    args = ap.parse_args()

    import torch
    from transformers import AutoModel

    device = ("cuda" if torch.cuda.is_available()
              else ("mps" if torch.backends.mps.is_available() else "cpu"))
    print(f"   device: {device}", flush=True)
    print(f"   loading {MODEL_ID} …", flush=True)
    # jina-clip-v2 ships a custom encode_image/encode_text — needs trust_remote_code
    model = AutoModel.from_pretrained(MODEL_ID, trust_remote_code=True).to(device)
    model.eval()

    processed = load_processed()
    pending, skipped = load_pending(processed)
    if args.limit:
        pending = pending[:args.limit]
    state = load_state()
    print(f"   queue: {len(pending):,} to embed "
          f"(already done {len(processed):,}, skipped {skipped:,})", flush=True)
    if not WORKER_UPSERT_URL and not args.no_upload:
        print("   ⚠️  JINA_UPSERT_URL not set — embeddings go to disk only; "
              "set it or pass --no-upload", flush=True)

    upload_buf = []

    def embed_and_store(items):
        """items: list of (art_id, e_id, img_url, PIL.Image). Embed → disk → queue upload."""
        if not items:
            return
        imgs = [it[3] for it in items]
        try:
            with torch.no_grad():
                # jina-clip-v2: returns L2-normalized float vectors (numpy)
                vecs = model.encode_image(imgs, truncate_dim=EMBED_DIM)
        except Exception as ex:
            print(f"  ⚠️ GPU error on batch of {len(items)}: {str(ex)[:120]}", flush=True)
            for art_id, e_id, *_ in items:
                state['total_failed'] += 1
            return
        for (art_id, e_id, img_url, _img), vec in zip(items, vecs):
            values = [float(x) for x in (vec.tolist() if hasattr(vec, 'tolist') else list(vec))]
            append_jsonl(OUTPUT_FILE, {"id": art_id, "e": e_id, "values": values})
            append_processed(art_id)            # only AFTER the vector is on disk
            state['total_success'] += 1
            upload_buf.append({"id": art_id, "values": values,
                               "metadata": {"e": e_id, "src": img_url}})

    def flush_uploads(force=False):
        if args.no_upload:
            upload_buf.clear()
            return
        while len(upload_buf) >= UPLOAD_BATCH or (force and upload_buf):
            chunk = upload_buf[:UPLOAD_BATCH]
            del upload_buf[:UPLOAD_BATCH]
            ok, err = upload_batch(chunk)
            if ok:
                state['total_upserted'] += len(chunk)
            else:
                state['total_upload_retry'] += len(chunk)
                for v in chunk:
                    append_jsonl(RETRY_FILE, v)
                if err:
                    print(f"  ⚠️ upload failed ({err}) → queued to retry", flush=True)

    buf = []
    done = 0
    with ThreadPoolExecutor(max_workers=PREFETCH_WORKERS) as pool:
        for art_id, e_id, img_url, image, err in pool.map(download_image, pending):
            done += 1
            if err or image is None:
                state['total_failed'] += 1
                append_processed(art_id)         # don't retry a dead image forever
            else:
                buf.append((art_id, e_id, img_url, image))
                if len(buf) >= GPU_BATCH:
                    embed_and_store(buf); buf = []
                    flush_uploads()
            if done % 200 == 0:
                save_state(state)
                print(f"  …{done:,}/{len(pending):,}  ok={state['total_success']:,} "
                      f"fail={state['total_failed']:,} up={state['total_upserted']:,}", flush=True)
        embed_and_store(buf)
        flush_uploads(force=True)

    save_state(state)
    print(f"\n✅ done — embedded={state['total_success']:,} "
          f"failed={state['total_failed']:,} uploaded={state['total_upserted']:,} "
          f"retry_queued={state['total_upload_retry']:,}", flush=True)
    print(f"   vectors on disk: {OUTPUT_FILE}", flush=True)


if __name__ == '__main__':
    main()
