#!/usr/bin/env python3
"""
SigLIP missing-permanent embedder
=================================

Reads `permanent_missing_pending.jsonl` (one record per line:
`{"id": ..., "e": exhibition_id, "i": image_url}`) — generated by
`scripts/build_permanent_missing.py` — and embeds every artwork that
isn't already in `siglip_processed_ids.txt`.

The pipeline mirrors `run_siglip_targeted.py` but is **queue-driven**
(no exhibition list, no manifest cross-reference at run time) so it can
target the exact gap left in the vector store with no chance of skipping
items because their parent collection wasn't enumerated upstream.

Save guarantees ("nothing gets lost")
-------------------------------------
1. Every successful embedding is **first** written to disk
   (`embedding_results/siglip_missing_permanent_embeddings.jsonl`) before
   `siglip_processed_ids.txt` is updated. If the script crashes mid-flight,
   nothing is recorded as "processed" without its vector also being on disk.
2. Cloudflare upload is a separate phase. A successful disk write counts
   as success even if the upload fails — the embedding can be re-uploaded
   later from the JSONL by `scripts/upload_to_vectorize.py` (see README).
3. Failed uploads are recorded to `siglip_upload_retry_missing.jsonl`
   so they can be replayed without re-running the GPU pipeline.
4. The `siglip_processed_ids.txt` master list is shared with every other
   embedding script in this repo, so re-running this script is a no-op
   for already-embedded items (it simply skips them).
5. All file writes are guarded by a `threading.Lock`.

Inputs
------
- `permanent_missing_pending.jsonl` (queue, generated by
  `build_permanent_missing.py`)
- `siglip_processed_ids.txt` (master ID list — read on startup, appended
  during run)

Outputs
-------
- `embedding_results/siglip_missing_permanent_embeddings.jsonl` (vectors)
- `siglip_failed_missing_permanent.jsonl` (image fetch / GPU failures)
- `siglip_upload_retry_missing.jsonl` (Cloudflare upload failures —
  vectors are still on disk in the embeddings file above)
- `siglip_state_missing_permanent.json` (running totals, resumable)
- `MISSING_EMBEDDING_PROGRESS.md` (live human-readable dashboard)

Run
---
    /usr/local/bin/python3.10 scripts/run_siglip_missing_permanent.py

Resume on crash: just run it again. The processed-ID list filters
already-done items.
"""
import json
import os
import gc
import time
import datetime
import threading
import traceback
from io import BytesIO
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

import torch
import urllib3
import requests
from PIL import Image
from transformers import AutoProcessor, AutoModel
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ── Paths ───────────────────────────────────────────────────────────────
ROOT             = Path(__file__).resolve().parents[1]
PENDING_FILE     = ROOT / 'permanent_missing_pending.jsonl'
PROCESSED_FILE   = ROOT / 'siglip_processed_ids.txt'
OUTPUT_DIR       = ROOT / 'embedding_results'
OUTPUT_FILE      = OUTPUT_DIR / 'siglip_missing_permanent_embeddings.jsonl'
FAILED_FILE      = ROOT / 'siglip_failed_missing_permanent.jsonl'
UPLOAD_RETRY     = ROOT / 'siglip_upload_retry_missing.jsonl'
STATE_FILE       = ROOT / 'siglip_state_missing_permanent.json'
DASHBOARD_FILE   = ROOT / 'MISSING_EMBEDDING_PROGRESS.md'

OUTPUT_DIR.mkdir(exist_ok=True)

# ── Model & runtime config ──────────────────────────────────────────────
WORKER_UPSERT_URL = "https://armin-semantic-search.armin-art.workers.dev/upsert"
MODEL_ID          = "google/siglip-base-patch16-224"
PREFETCH_WORKERS  = 6      # threads downloading images concurrently
GPU_BATCH         = 4      # SigLIP forward-pass batch size on MPS
UPLOAD_BATCH      = 50     # vectors per Cloudflare /upsert call
DOWNLOAD_TIMEOUT  = 12     # seconds per image fetch
UPLOAD_TIMEOUT    = 30
DOWNLOAD_HEADERS  = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/122.0.0.0 Safari/537.36",
    "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
}

# ── HTTP session with retries ──────────────────────────────────────────
session = requests.Session()
retries = Retry(total=2, backoff_factor=0.5,
                status_forcelist=[500, 502, 503, 504])
session.mount('http://',  HTTPAdapter(max_retries=retries,
                                      pool_connections=20, pool_maxsize=20))
session.mount('https://', HTTPAdapter(max_retries=retries,
                                      pool_connections=20, pool_maxsize=20))

file_lock = threading.Lock()


# ── State helpers ──────────────────────────────────────────────────────
def load_state():
    state = {
        "total_success": 0, "total_failed": 0, "total_upserted": 0,
        "total_upload_retry": 0,
        "exh_done": {}, "exh_failed": {},
        "started_at": datetime.datetime.now().isoformat(),
    }
    if STATE_FILE.exists():
        try:
            state.update(json.loads(STATE_FILE.read_text()))
        except Exception:
            pass
    return state


def save_state(state):
    with file_lock:
        STATE_FILE.write_text(json.dumps(state, ensure_ascii=False, indent=2))


def load_processed():
    processed = set()
    if PROCESSED_FILE.exists():
        with open(PROCESSED_FILE, encoding='utf-8') as f:
            for line in f:
                s = line.strip()
                if s:
                    processed.add(s)
    return processed


def load_pending(processed):
    """Yield {id,e,i} dicts that are NOT yet in `processed`."""
    out = []
    skipped_already = 0
    if not PENDING_FILE.exists():
        raise SystemExit(f"[fatal] {PENDING_FILE} missing — run "
                         "scripts/build_permanent_missing.py first")
    with open(PENDING_FILE) as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            try:
                rec = json.loads(s)
            except Exception:
                continue
            if not rec.get('id') or not rec.get('i'):
                continue
            if rec['id'] in processed:
                skipped_already += 1
                continue
            out.append(rec)
    return out, skipped_already


# ── Image download (runs in thread pool) ───────────────────────────────
def download_image(item):
    art_id = item['id']
    img_url = item['i']
    e_id = item.get('e', '')
    try:
        resp = session.get(img_url, timeout=DOWNLOAD_TIMEOUT,
                           verify=False, headers=DOWNLOAD_HEADERS)
        if resp.status_code == 200:
            image = Image.open(BytesIO(resp.content)).convert("RGB")
            return art_id, e_id, img_url, image, None
        return art_id, e_id, img_url, None, f"HTTP {resp.status_code}"
    except Exception as ex:
        return art_id, e_id, img_url, None, str(ex)[:120]


# ── Cloudflare upload ──────────────────────────────────────────────────
def upload_batch(batch):
    """POST a batch to /upsert. Returns (success: bool, error: str|None)."""
    if not batch:
        return True, None
    try:
        resp = session.post(WORKER_UPSERT_URL,
                            json={"vectors": batch},
                            timeout=UPLOAD_TIMEOUT)
        if resp.status_code == 200:
            return True, None
        return False, f"HTTP {resp.status_code}: {resp.text[:120]}"
    except Exception as ex:
        return False, str(ex)[:120]


def append_jsonl(path, rec):
    """Append one record to a JSONL file under the lock."""
    with file_lock:
        with open(path, 'a', encoding='utf-8') as f:
            f.write(json.dumps(rec, ensure_ascii=False) + '\n')


def append_processed(art_id):
    with file_lock:
        with open(PROCESSED_FILE, 'a', encoding='utf-8') as f:
            f.write(art_id + '\n')


# ── Dashboard ──────────────────────────────────────────────────────────
def update_dashboard(state, current_exh, total_pending, elapsed):
    done = state['total_success']
    speed = done / elapsed if elapsed > 0 else 0.0
    eta = ((total_pending - done) / speed / 60.0) if speed > 0 else 0.0
    lines = [
        "# 🎨 Missing Permanent Embeddings — live progress",
        "",
        f"> **Updated**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"> **Pending total**: {total_pending:,}",
        f"> **Embedded**: {done:,} | **Failed**: {state['total_failed']:,} | "
        f"**Uploaded**: {state['total_upserted']:,} | "
        f"**Upload-retry queued**: {state['total_upload_retry']:,}",
        f"> **Speed**: {speed:.1f}/s | **ETA**: {eta:.1f} min",
        "",
        "| Exhibition ID | Embedded | Failed |",
        "|:---|---:|---:|",
    ]
    seen = set(state['exh_done'].keys()) | set(state['exh_failed'].keys())
    for e in sorted(seen):
        ok = state['exh_done'].get(e, 0)
        bad = state['exh_failed'].get(e, 0)
        marker = " 🔥" if e == current_exh else ""
        lines.append(f"| {e}{marker} | {ok:,} | {bad:,} |")
    try:
        DASHBOARD_FILE.write_text('\n'.join(lines))
    except Exception:
        pass


# ════════════════════════════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════════════════════════════
def main():
    print("🚀 SigLIP missing-permanent embedder", flush=True)

    device = ("mps" if torch.backends.mps.is_available()
              else ("cuda" if torch.cuda.is_available() else "cpu"))
    print(f"   device: {device}", flush=True)

    print("   loading model …", flush=True)
    model = AutoModel.from_pretrained(MODEL_ID).to(device)
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    model.eval()

    state = load_state()
    processed = load_processed()
    print(f"   processed-IDs already on disk: {len(processed):,}",
          flush=True)

    pending, skipped = load_pending(processed)
    print(f"   pending queue size: {len(pending):,} "
          f"({skipped:,} already done — skipped)", flush=True)
    if not pending:
        print("✨ Nothing to do — all permanent items are embedded.",
              flush=True)
        return

    upload_buf = []  # accumulating list of {id, values, metadata}
    start_time = time.time()
    session_done = 0
    total_pending = len(pending)

    def flush_gpu(buf, current_exh):
        """Encode a batch of PIL images and write embeddings to disk."""
        nonlocal session_done
        if not buf:
            return
        try:
            inputs = processor(images=[b[3] for b in buf],
                               return_tensors="pt", padding=True).to(device)
            with torch.no_grad():
                feats = model.get_image_features(**inputs)
            feats = feats / feats.norm(p=2, dim=-1, keepdim=True)
            vecs = feats.cpu().numpy().tolist()
            del inputs, feats
            for b in buf:
                b[3].close()

            for i, (aid, eid, _url, _img, _err) in enumerate(buf):
                vec = vecs[i]
                # ① write embedding to disk first
                append_jsonl(OUTPUT_FILE, {"id": aid, "e": eid, "vector": vec})
                # ② only then mark processed
                append_processed(aid)
                processed.add(aid)
                state['total_success'] += 1
                state['exh_done'][eid] = state['exh_done'].get(eid, 0) + 1
                session_done += 1
                # ③ queue for upload
                upload_buf.append({"id": aid,
                                   "values": vec,
                                   "metadata": {"e": eid}})

        except Exception as gpu_e:
            err_str = (str(gpu_e) + ' :: ' + traceback.format_exc())[:300]
            print(f"  ⚠️ GPU error on batch of {len(buf)}: {err_str[:120]}",
                  flush=True)
            for aid, eid, url, _img, _ in buf:
                state['total_failed'] += 1
                state['exh_failed'][eid] = state['exh_failed'].get(eid, 0) + 1
                append_jsonl(FAILED_FILE,
                             {"id": aid, "e": eid, "error": err_str,
                              "url": url, "stage": "gpu"})
                append_processed(aid)
                processed.add(aid)

        # ④ upload in fixed-size chunks
        while len(upload_buf) >= UPLOAD_BATCH:
            chunk = upload_buf[:UPLOAD_BATCH]
            del upload_buf[:UPLOAD_BATCH]
            ok, err = upload_batch(chunk)
            if ok:
                state['total_upserted'] += len(chunk)
            else:
                # NOT a data-loss event — embedding is on disk.
                # Queue for later retry.
                state['total_upload_retry'] += len(chunk)
                for v in chunk:
                    append_jsonl(UPLOAD_RETRY,
                                 {"id": v["id"],
                                  "vector": v["values"],
                                  "e": v["metadata"]["e"],
                                  "error": err})
                print(f"  ⚠️ upload failed (saved to retry queue): {err}",
                      flush=True)

    # Group pending by exhibition for nicer logging
    by_exh = {}
    for rec in pending:
        by_exh.setdefault(rec['e'], []).append(rec)
    exh_list = sorted(by_exh.items(), key=lambda kv: -len(kv[1]))

    for exh_id, items in exh_list:
        print(f"\n🏛️  [{exh_id}] {len(items):,} items", flush=True)

        with ThreadPoolExecutor(max_workers=PREFETCH_WORKERS) as executor:
            futures = {executor.submit(download_image, item): item
                       for item in items}
            gpu_buf = []

            for future in as_completed(futures):
                aid, eid, url, image, err = future.result()

                if err or image is None:
                    state['total_failed'] += 1
                    state['exh_failed'][eid] = (
                        state['exh_failed'].get(eid, 0) + 1)
                    append_jsonl(FAILED_FILE,
                                 {"id": aid, "e": eid, "error": err,
                                  "url": url, "stage": "download"})
                    append_processed(aid)
                    processed.add(aid)
                    session_done += 1
                    continue

                gpu_buf.append((aid, eid, url, image, None))
                if len(gpu_buf) >= GPU_BATCH:
                    flush_gpu(gpu_buf[:GPU_BATCH], exh_id)
                    gpu_buf = gpu_buf[GPU_BATCH:]

                if session_done > 0 and session_done % 100 == 0:
                    elapsed = time.time() - start_time
                    speed = session_done / elapsed
                    print(f"  ⚡ {session_done:,} in this run "
                          f"({speed:.1f}/s) | "
                          f"OK {state['total_success']:,} "
                          f"FAIL {state['total_failed']:,} "
                          f"UP {state['total_upserted']:,} "
                          f"RETRY {state['total_upload_retry']:,}",
                          flush=True)
                    save_state(state)
                    gc.collect()
                    update_dashboard(state, exh_id, total_pending, elapsed)

            # Drain GPU buffer for this exhibition
            flush_gpu(gpu_buf, exh_id)
            gpu_buf = []

        save_state(state)
        elapsed = time.time() - start_time
        update_dashboard(state, exh_id, total_pending, elapsed)
        print(f"  ✅ {exh_id}: done "
              f"(ok={state['exh_done'].get(exh_id,0)} "
              f"fail={state['exh_failed'].get(exh_id,0)})",
              flush=True)

    # Final upload flush
    if upload_buf:
        ok, err = upload_batch(upload_buf)
        if ok:
            state['total_upserted'] += len(upload_buf)
        else:
            state['total_upload_retry'] += len(upload_buf)
            for v in upload_buf:
                append_jsonl(UPLOAD_RETRY,
                             {"id": v["id"], "vector": v["values"],
                              "e": v["metadata"]["e"], "error": err})

    save_state(state)
    elapsed = time.time() - start_time
    update_dashboard(state, "(done)", total_pending, elapsed)
    print(f"\n🎊 done. ok={state['total_success']:,} "
          f"fail={state['total_failed']:,} "
          f"uploaded={state['total_upserted']:,} "
          f"upload_retry={state['total_upload_retry']:,} "
          f"in {elapsed/60:.1f} min", flush=True)


if __name__ == '__main__':
    main()
